version: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=monmotdepasse
      - N8N_HOST=ton-domaine-ou-url-de-render
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n-2owh.onrender.com
      - EXECUTIONS_PROCESS=main
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n-2owh.onrender.com
      - N8N_CORS_ORIGINS=https://n8n-2owh.onrender.com
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:
